### PR TITLE
refactor ReadKey.pm

### PR DESCRIPTION
**Pull request by rurban**
auto-generate the platform-specific parts at installation.
expand blockoptions specific variants already at installation,
demand-load Carp, remove unneeded AutoLoader,
harmonize formatting.

Configure.pm, genchars.pl: reformatting, support -Dfortify_inc and
cperl.

Makefile.PL: support ReadKey_pm.PL, add SIGN, fix pure_site_install,
fix realclean

META.yml: removed, auto-generated with make dist

### CODE REVIEW

**Comment by jonathanstowe** [comment]
Hi,
thanks for this, it looks good but would it be possible to split this into two commits, one with the formatting changes and the other implementing the generation of the ReadKey.pm?  This will make it easier to revert if there is a problem down the line.

Thanks again.

**Comment by rurban** [comment]
sure, will push force to this branch

**Comment by jonathanstowe** [comment]
Cool, thanks :)

The problems I foresee are with upstream packagers.  I'm going to make a 'dev' _RC1 release with this to get a flavour of how much they will scream before making a proper release.

Thanks again.

**Comment by rurban** [comment]
Shouldn't I seperate the reformatting of the eval code sections in the .pm also? There was also a lot of reformatting going on.

**Comment by rurban** [comment]
Ah, too late. I was in the movies :)
Thanks!

**Pull request merged**
